### ISSUE TITLE
Materializando el diseño de tu aplicacion

### ISSUE THREAD

**Issue by jose-ig-cabrera** [angular-bolivia/meetup#10]
# Me gustaría...  

`(Selecciona con una "x" => [x])`

- [x] **Dar una Charla Técnica:** 
- [ ] **Dar un Code Lab**

## Descripción de la Charla Técnica o Code Lab
Al momento de diseñar una aplicacion normalmente se invierte demasiado tiempo pensando en el flujo y diseño de la misma. En esta charla veremos las ventajas que nos da Material sobre el diseño convencional y como sacarle el jugo con un buen manejo de experiencia de usuario usando material angular 

## Acerca de Ti
Jose es un UX Designer entusiasta, le agrada aprender mas acerca del area de frontend y UX/UI e interiorizarse con las nuevas propuestas de material design. 

## Username en Twitter
@JosIgCab

## Username en Slack(Angular Bolivia Team)
@JosUXCab

## Ciudad de Residencia
Cochabamba

## Tiempo 
- 30 minutos
## Nivel
- Básico

## ¿Has dado esta charla antes?
- No

**Comment by luixaviles** [comment]
¡Hola @jose-ig-cabrera !

Estamos muy contentos de anunciar que tu propuesta ha sido aceptada por el equipo de organización.
Estaremos coordinando detalles a través de nuestro team en Slack. Te pedimos que te pongas en contacto con nosotros para poder coordinar y resolver las dudas que tengas.

¡Saludos!
