### ISSUE TITLE
JIT vs AOT con Angular

### ISSUE THREAD

**Issue by renecardozo** [angular-bolivia/meetup#11]
# Me gustaría...  

- [x] **Dar una Charla Técnica:** 

## Descripción de la Charla Técnica o Code Lab

En esta charla se dara una breve explicacion acerca de estos features que estan presentes en angular de los cuales muchos no conocen pero todos lo usan, se dara a conocer la ventajas de cada uno y como estos repercuten en el performance de aplicaciones hechas con angular.
## Acerca de Ti
Rene tambien conocido como neko es un desarrollador de software con mas de 3 años de experiencia trabajando en un principio con AngularJs y este ultimo tiempo con Angular 2/4, actualmente trabaja para un empresa del rubro en Cochabamba.
## Username en Twitter
@cardozorene

## Username en Slack(Angular Bolivia Team)
@neko

## Ciudad de Residencia
Cochabamba-Bolivia

## Tiempo 
¿Qué tiempo necesitas para dar la charla?
Media hora
## Nivel
¿Cuál es el nivel de tu charla?) Básico, Intermedio, Avanzado
Intermedio
## ¿Has dado esta charla antes?
Si

**Comment by luixaviles** [comment]
¡Hola!

Estamos muy contentos de recibir tu propuesta. Pero debido a limitaciones de tiempo para nuestro meetup,   no podremos tomarla en cuenta en esta ocasión. Sin embargo, nos gustaría contar con tu participación en nuestro siguiente evento.
Te pedimos que te pongas en contacto con nosotros para poder coordinar y resolver las dudas que tengas.

¡Saludos!

**Comment by neko** [comment]
dont @ me
