### ISSUE TITLE
Framework vs Libreria, una comparacion de Angular y React.

### ISSUE THREAD

**Issue by renecardozo** [angular-bolivia/meetup#16]
# Me gustaría...  

- [x] **Charla Tecnica**

## Descripción de la Charla Técnica

En estar charla se dara a conocer alguna de las caracteristicas principales que difirieren entre ambos, se responderas preguntas tales como cual de ellos es un framework o una libreria? Ambos usan el concepto de component? , se mostrara porciones de codigo en base a un ejemplo de sus formas diferentes de crear un una vista. Siendo ambos orientados a la web y posibles a ser desarrolado en javascript es importante saber alguna virtudes y defectos de ambos con el fin de tomar la mejor desicion cuando se tenga que desarrollas algun sitio web.

## Acerca de Ti
Mi Nombre es Rene Alias "Neko" soy desarrollador de Software desde hace mas de 4 anios,  trabajo como FullStack Developer en Truextend. Mi pasion es  aprender nuevas tecnologias, aun estoy enamorado de Angular pero eso me liga a no  aprender mas y mas. Me gusta compartir cualquier conocimiento aprendido y ayudar en el aprendizaje a los demas.

## Username en Twitter
@renecardozo

## Username en Slack(Angular Bolivia Team)
@neko

## Ciudad de Residencia
Cochambama

## Tiempo 
30 min

## Nivel
Intermedio, es necesario tener concocimiento acerca de javascript, html y css.

## ¿Has dado esta charla antes?
Si

**Comment by renecardozo** [comment]
[FrameworkVSlibrary.pptx](https://github.com/angular-bolivia/meetup/files/2003417/FrameworkVSlibrary.pptx)

**Comment by neko** [comment]
😡
