### ISSUE TITLE
Hybrid Application angularjs/angular, how to use components angular inside angularjs

### ISSUE THREAD

**Issue by renecardozo** [angular-bolivia/meetup#2]
# Me gustaría...  

`(Selecciona con una "x" => [x])`

- [x] **Dar una Charla Técnica:** 
- [ ] **Dar un Code Lab**

## Descripción de la Charla Técnica

Esta guía describe las herramientas integradas para migrar componentes hechos en angular a applicaciones hechas en angularjs usando el modulo ngUpgrade.

Algunas aplicaciones serán más fáciles de actualizar que otras, y hay muchas maneras de hacerlo más fácil para usted. Es posible preparar y alinear las aplicaciones AngularJS con Angular incluso antes de comenzar el proceso de actualización. Estos pasos de la preparación están todo sobre hacer el código más disociado, más maintainable, y alineado mejor con las herramientas de desarrollo modernas. Eso significa que además de facilitar la actualización, también mejorará las aplicaciones AngularJS existentes.

Una de las claves para una actualización exitosa es hacerlo de forma incremental, ejecutando los dos marcos lado a lado en la misma aplicación y portando los componentes AngularJS a Angular uno por uno. Esto hace posible actualizar incluso aplicaciones grandes y complejas sin interrumpir otros negocios, porque el trabajo se puede realizar de forma colaborativa y extenderse por un período de tiempo. El módulo de actualización en Angular ha sido diseñado para mejorar de forma incremental sin problemas.

## Acerca de Ti
Soy FullStack MEAN developer, trabajo mas de 3 años con angularjs y a partir del 2017 con angular2/4,
Actualmente trabajo como front-end developer usando angularjs y angular.

## Username en Twitter
@CardozoRene

## Username en Slack(Angular Bolivia Team)
@neko

## Ciudad de Residencia
Cochabamba-Bolivia

## Tiempo 
Media hora

## Nivel
 Intermedio

## ¿Has dado esta charla antes?
Si

**Comment by luixaviles** [comment]
@renecardozo Gracias por la propuesta!
Por favor, np olvides actualizar los detalles de tu charla en el mismo issue. Puedes ver un ejemplo [aqui](https://github.com/angular-bolivia/meetup/issues/1)

**Comment by renecardozo** [comment]
@luixaviles ya esta actualizado.

**Comment by luixaviles** [comment]
@renecardozo Excelente. Muchas gracias @renecardozo

**Comment by neko** [comment]
no hablo espanol amigo @renecardozo
