### ISSUE TITLE
"ng add @angular/pwa" and that's it

### ISSUE THREAD

**Issue by mauricioarce** [angular-bolivia/meetup#20]
# Me gustaría...  

`(Selecciona con una "x" => [x])`

- [x] **Dar una Charla Técnica:** 
- [ ] **Dar un Code Lab**
- [ ] **Charla corta**

## Nivel
`(Selecciona con una "x" => [x])`

- [ ] **Básico:** 
- [x] **Intermedio**
- [ ] **Avanzado**

## Descripción de la Charla Técnica o Code Lab
En la charla se dará una breve introducción a lo que son las Progressive Web Apps, su potencial y cómo se diferencian de otro tipo de aplicaciones. Además, se mostrarán los pasos necesarios para crear una PWA con Angular y publicarla usando Github pages.

## Acerca de Ti
Mauricio es desarrollador de software. Muy apasionado por la tecnología en general, la programación y en especial por el desarrollo con Angular.

## Username en Twitter
@mauri075

## Username en Slack(Angular Bolivia Team)
@mauri075

## Ciudad de Residencia
Cochabamba

## Tiempo 
20 a 30 minutos

## Nivel
Intermedio

## ¿Has dado esta charla antes?
No

**Comment by mauricioarce** [comment]
Hola,

Buenísimo, mil gracias. Confirmo mi participación en el meetup.

Saludos,
Mauricio

**Comment by lizzymendivil** [comment]
¡Te esperamos Mauricio!
Por favor trata de estar puntual y planifica tu tiempo para estar en toda la sesión (9.00 AM - 12.15 PM)

**Correción:** El evento será el día sábado 13 de Octubre
