### ISSUE TITLE
Blockchain + Angular | proposed by @whiletrueothis

### ISSUE THREAD

**Issue by whiletruedothis** [angular-bolivia/meetup#21]
# Me gustaría...  

`(Selecciona con una "x" => [x])`

- [ ] **Dar una Charla Técnica:** 
- [ ] **Dar un Code Lab**
- [x] **Charla corta**

## Nivel
`(Selecciona con una "x" => [x])`

- [x] **Básico:** 
- [ ] **Intermedio**
- [ ] **Avanzado**

## Descripción de la Charla Técnica o Code Lab
En esta charla se hablará acerca de blockchain y del desallorro del mismo con Angular, en el cual se responderán preguntas como: ¿Qué es blockchain? ¿En qué casos se puede aplicar este tipo de soluciones? ¿Cuáles son las ventajas de usar este tipo de tecnologia? ¿Cómo empezar a desarrollar con esta tecnología? ¿Cómo trabajar con Angular y tecnologías blockchain?
 
## Acerca de Ti
Rodrigo es un estudiante de ingeniería de sistemas de 22 años, que se encuentra en el 4to año de la carrera de ingeniería de sistemas en la universidad Católica San Pablo Cochabamba. Es tutor de un grupo de estudio de Angular dentro de su univeridad. Fué tutor de cursos de web en la UMSS y python dentro del programa Global Shapers. Fué speaker en varios eventos locales organizados por la comunidad GDG Cochabamba y también dio una charla sobre Angular en el evento de software libre Flisol en Cochabamba.  Apasionado de los eventos de tecnología y ganador de la Hackaton nacional HackBo 2017. Intersado por la programación y los concursos de programación de la ACM, llegando a concursos lationoamericanos como uno de sus hitos de 2017. Actualmente se encuentra realizando su pasantía universitaria con tecologías de realidad virtual como pasante de la empresa Ancestral Gods.

## Username en Twitter
@whiletruedothis

## Username en Slack(Angular Bolivia Team)
@whiletruedothis

## Ciudad de Residencia
Cochabama

## Tiempo 
20 a 30 minutos

## Nivel
Básico

## ¿Has dado esta charla antes?
Si

**Comment by eduatro** [comment]
Hola @whiletruedothis,
Tenemos el gusto de informarte que tu charla fue seleccionada para el meetup del sabado 8 de septiembre de 9:10 a 9:40.
Por favor confirma la disponibilidad para ese dia.

Saludos
Angular bolivia
