### ISSUE TITLE
Optimistic UI and cancellable optimistic updates in Angular 2

### ISSUE THREAD

**Issue by carlos-olivera** [angular-bolivia/meetup#24]
# Me gustaría...  

`(Selecciona con una "x" => [x])`

- [x ] **Dar una Charla Técnica:** 
- [ ] **Dar un Code Lab**
- [ ] **Charla corta**

## Nivel
`(Selecciona con una "x" => [x])`

- [ ] **Básico:** 
- [ x] **Intermedio**
- [ ] **Avanzado**

## Descripción de la Charla Técnica o Code Lab
Optimistic UI and cancellable optimistic updates in Angular 2
Patrones y técnicas para ofrecer al usuario una mejor experiencia de uso al brindarle un feedback inmediato de sus acciones. Veremos un ejemplo "hecho a mano" con un end point REST estándar, y analizaremos como hace un trabajo similar Firebase y Meteor.

## Acerca de Ti
Emprendedor en TI y Full Stack Developer (ex game developer)

## Username en Twitter
@carlos_olivera

## Username en Slack(Angular Bolivia Team)
@carlos_olivera

## Ciudad de Residencia
Cochabamba

## Tiempo 
45m

## Nivel
Intermedio

## ¿Has dado esta charla antes?
Siempre hay una primera vez

**Comment by nicobytes** [comment]
Hola! @carlos-olivera 

Tenemos el gusto de informarte que tu charla fue seleccionada para el meetup del 8 de septiembre, de  09:00 a 12:15

Por favor confirmar la disponibilidad. Para este día!
