### ISSUE TITLE
Angular Lego

### ISSUE THREAD

**Issue by Guchster** [angular-bolivia/meetup#26]
# Me gustaría...  

- [x] **Dar una Charla Técnica:** 
- [x] **Dar un Code Lab**
- [ ] **Charla corta**

## Nivel

- [ ] **Básico:** 
- [x] **Intermedio**
- [ ] **Avanzado**

## Descripción de la Charla Técnica o Code Lab
Angular Lego es una charla técnica (así como un Code Lab) sobre como implementar una arquitectura modularizada y escalable mediante la encapsulación de componentes y módulos separados de acuerdo a su funcionalidad, donde cada módulo típico encapsula la vista, estilos, controlador, modelos (si aplica), servicio y routing necesarios para su funcionamiento independiente.

Se explicará la importancia de la implementación de lazy loading para disminuir los tiempos de carga de cada módulo y de la aplicación en general, incluyendo un módulo de routing para cada módulo.

Se hará hincapié en la utilización de módulos comunes y útiles en proyectos del día a día, como el CoreModule para servicios singleton, SharedModule para reutilizar componentes que se utilizan en muchos lugares de la aplicación y servicios no singleton, así como MaterialModule para un uso correcto de la librería de Angular Material.

## Acerca de Ti
Santiago es un persona detallista y dedicada con las cosas que le interesan, graduado como Ing. de Telecomunicaciones en la Universidad Católica Boliviana actualmente trabaja como especialista en desarrollo de software en VIVA, enfocando sus esfuerzos en el desarrollo con Angular y Electron; amante del futbol, la magia, la tecnología y los cubos rubik, siempre esta buscando algo nuevo que aprender y personas con quien compartir sus conocimientos.

## Username en Twitter
@Guchster24  (inactivo)

## Username en Slack(Angular Bolivia Team)
(No estoy en el Canal de Angular Bolivia Team)

## Ciudad de Residencia
Cochabamba

## Tiempo 
25 minutos charla.
40-60 minutos codelab.

## Nivel
Intermedio

## ¿Has dado esta charla antes?
No

**Comment by eduatro** [comment]
Hola @Guchster ,
Tenemos el gusto de informarte que tu charla fue seleccionada para el meetup del sabado 8 de septiembre de 10:20 a 10:50.
Por favor confirma la disponibilidad para ese dia.

Saludos
Angular Bolivia

**Comment by Guchster** [comment]
Confirmado!
