### ISSUE TITLE
Escribamos código limpio!

### ISSUE THREAD

**Issue by cmtp** [angular-bolivia/meetup#28]
# Me gustaría...  

`(Selecciona con una "x" => [x])`

- [x] **Dar una Charla Técnica:** 
- [ ] **Dar un Code Lab**
- [x] **Charla corta**

## Nivel
`(Selecciona con una "x" => [x])`

- [x] **Básico:** 
- [ ] **Intermedio**
- [ ] **Avanzado**

## Descripción de la Charla Técnica o Code Lab
Un programa puede llegar a tener miles de líneas de código, a medida que crece los desarrolladores pueden llegar a perderse si este no se encuentra bien estructurado, de ahí la importancia de que el código sea sencillo, fácil de extender, y bien documentado.
En esta charla veremos que es muy importante escribir código legible dentro de nuestras aplicaciones, algunos consejos de como escribir código limpio, y algunas herramientas que nos ayudarán en el día a día.

## Acerca de Ti
Christian es desarrollador de software, apasionado de Javascript y el open source, trabaja como desarrollador Frontend en Truextend, siempre en constante aprendizaje.

## Username en Twitter
@ctola91

## Username en Slack(Angular Bolivia Team)
@ctola

## Ciudad de Residencia
Cochabamba

## Tiempo 
25 min.

## Nivel
Básico

## ¿Has dado esta charla antes?
No

**Comment by nicobytes** [comment]
Hola! @cmtp!

Tenemos el gusto de informarte que tu charla fue seleccionada para el meetup del 8 de septiembre, de 9:45 - 10:15 am

Por favor confirmar la disponibilidad. Para este día!

**Comment by carlos-olivera** [comment]
Confirmado.

Gracias!

**Comment by cmtp** [comment]
Hola @nicobytes,

confirmado.

**Comment by cmtp** [comment]
Christian Marcelo Tola Pacheco

https://es.gravatar.com/userimage/105024441/12fe4198bafd8684ecfe7973053c9611.jpg
