### ISSUE TITLE
Be a Pokemon master with JavaScript frameworks

### ISSUE THREAD

**Issue by devfer-js** [angular-bolivia/meetup#30]
# Me gustaría...  

`(Selecciona con una "x" => [x])`

- [ ] **Dar una Charla Técnica:** 
- [ ] **Dar un Code Lab**
- [x] **Charla corta**

## Nivel
`(Selecciona con una "x" => [x])`

- [x] **Básico:** 
- [ ] **Intermedio**
- [ ] **Avanzado**

## Descripción de la Charla Técnica o Code Lab
En esta charla hablaremos sobre los frameworks de javascript más conocidos para ser más en específicos hablaremos sobre Angular, Vue.js y React.js . En la charla se hablará sobre las fortalezas y debilidades de cada uno, con cual empezar o como elegir el framework que mas te convenga y cuál será su camino de cada uno, contando los obstáculos de cada framework. Ademas de ejemplos de uso de cada uno.Esta charla esta dirigida a personas que están empezando con el desarrollo web y están en un conflicto de que camino elegir o informarse sobre otras tecnologías. 

## Acerca de Ti
Fernando es una persona entusiasta y emocionada por la tecnología, es un estudiante del colegio san Agustín, actualmente se está concentrando en aprender y dominar las tecnologías web, Es fundador y líder de despair developers, un grupo de jóvenes que hacen videojuegos. También es profesor privado de programación con lenguajes de c++ y javascript. Su pasatiempo es leer literatura juvenil. A el le gusta : el anime, la lluvia y escuchar Jazz.
## Username en Twitter
@ferkki2

## Username en Slack(Angular Bolivia Team)
@ferkki

## Ciudad de Residencia
Cochabamba

## Tiempo 
15 min 

## Nivel
Basico

## ¿Has dado esta charla antes?
No

**Comment by lizzymendivil** [comment]
¡Hola Fernando!

Queremos informarte que tu propuesta fue elegida para nuestro meetup Angular Bolivia Octubre 2018 que será llevado a cabo el día sábado 16 de Octubre a partir de las 9.00 AM

Por favor, necesitamos tu **confirmación** respondiendo este mensaje.

¡Gracias!

**Comment by devfer-js** [comment]
> ¡Hola Fernando!
> 
> Queremos informarte que tu propuesta fue elegida para nuestro meetup Angular Bolivia Octubre 2018 que será llevado a cabo el día sábado 16 de Octubre a partir de las 9.00 AM
> 
> Por favor, necesitamos tu **confirmación** respondiendo este mensaje.
> 
> ¡Gracias!
Confirmado que ese dia asisitire

**Comment by lizzymendivil** [comment]
Lo siento, quise decir 13 de Octubre. :D

**Comment by lizzymendivil** [comment]
¡Te esperamos Fernando!
Por favor trata de estar puntual y planifica tu tiempo para estar en toda la sesión (9.00 AM - 12.15 PM)

**Correción:** El evento será el día sábado 13 de Octubre

**Comment by devfer-js** [comment]
> ¡Te esperamos Fernando!
> Por favor trata de estar puntual y planifica tu tiempo para estar en toda la sesión (9.00 AM - 12.15 PM)
> 
> **Correción:** El evento será el día sábado 13 de Octubre

ok super ahi estare !!!!
