### ISSUE TITLE
Dashboards con Componentes dinámicos 

### ISSUE THREAD

**Issue by Oscarsgc** [angular-bolivia/meetup#5]
# Me gustaría...  

`(Selecciona con una "x" => [x])`

- [x] **Dar una Charla Técnica:** 
- [ ] **Dar un Code Lab**

## Descripción de la Charla Técnica o Code Lab
Dentro de una aplicación web las vistas pueden ser estáticas (programadas y no modificables) o dinámicas(modificables en tiempo de ejecución) de acuerdo al requerimiento y funcionalidad de la misma. En esta charla veremos el uso del API de Angular para crear componentes dinámicamente para ser utilizados en un dashboard a través de un proyecto de ejemplo liberado para su uso y consulta posterior.

## Acerca de Ti
Ingeniero de Software, desarrollador Web, apasionado por la tecnología, 2 años trabajando con AngularJS y Angular.

## Username en Twitter
@Oscar_sgc

## Username en Slack(Angular Bolivia Team)
@oscar_sgc

## Ciudad de Residencia
Cochabamba

## Tiempo 
30 minutos

## Nivel
Intermedio

## ¿Has dado esta charla antes?
No

**Comment by luixaviles** [comment]
¡Hola @Oscarsgc !

Estamos muy contentos de anunciar que tu propuesta ha sido aceptada por el equipo de organización
Estaremos coordinando detalles a través de nuestro team en. Te pedimos que te pongas en contacto con nosotros para poder coordinar y resolver las dudas que tengas.

¡Saludos!
