### ISSUE TITLE
Convenciones para tus CSS? BEM!.

### ISSUE THREAD

**Issue by klozano** [angular-bolivia/meetup#6]
# Me gustaría...  

`(Selecciona con una "x" => [x])`

- [X] **Dar una Charla Técnica:** 
- [ ] **Dar un Code Lab**

## Descripción de la Charla Técnica o Code Lab
Hoy en día, nombrar tus estilos se convirtió en una tarea utópica, a tal punto que en algún momento llegamos considerarlo como algo irrelevante y no le damos la debida importancia.
Pero momento!, existen metodologías para organizar tus CSS y veremos porque que BEM es una de las metodologías mas atractivas.

## Acerca de Ti
Kenji es Desarrollador de Software en Truextend, trabaja con Javascript desde hace varios años. Fanático por Meteor y Apollo 🚀.

## Username en Twitter
@kenji_lozano

## Username en Slack(Angular Bolivia Team)
@kenji

## Ciudad de Residencia
Cochabamba

## Tiempo 
30min

## Nivel
Básico

## ¿Has dado esta charla antes?
No

**Comment by luixaviles** [comment]
¡Hola @klozano !

Estamos muy contentos de recibir tu propuesta. Pero debido a limitaciones de tiempo para nuestro meetup,   no podremos tomarla en cuenta en esta ocasión. Sin embargo, nos gustaría contar con tu participación en nuestro siguiente evento.
Te pedimos que te pongas en contacto con nosotros para poder coordinar y resolver las dudas que tengas.

¡Saludos!
