### ISSUE TITLE
Angular + Meteor. Real Time!

### ISSUE THREAD

**Issue by klozano** [angular-bolivia/meetup#7]
# Me gustaría...  

`(Selecciona con una "x" => [x])`

- [X] **Dar una Charla Técnica:** 
- [ ] **Dar un Code Lab**

## Descripción de la Charla Técnica o Code Lab
El perfecto stack!. Trabajar con Real Time Apps nunca fue mas facil!. Revisaremos como integrar el Real Time de Meteor con Angular 4. Veremos que es DDP y lo sencillo que es trabajar con mongodb.

## Acerca de Ti
Kenji es un desarrollador de software, trabajando con javascript desde hace varios años. Fanático por Meteor y Apollo Stack 🚀.

## Username en Twitter
@kenji_lozano

## Username en Slack(Angular Bolivia Team)
@kenji

## Ciudad de Residencia
Cochabamba

## Tiempo 
30min

## Nivel
Intermedio

## ¿Has dado esta charla antes?
No

**Comment by luixaviles** [comment]
¡Hola @klozano !

Estamos muy contentos de anunciar que tu propuesta ha sido aceptada por el equipo de organización.
Estaremos coordinando detalles a través de nuestro team en Slack. Te pedimos que te pongas en contacto con nosotros para poder coordinar y resolver las dudas que tengas.

¡Saludos!
