### ISSUE TITLE
Apollo Stack y Angular. Es posible?

### ISSUE THREAD

**Issue by klozano** [angular-bolivia/meetup#8]
# Me gustaría...  

`(Selecciona con una "x" => [x])`

- [X] **Dar una Charla Técnica:** 
- [ ] **Dar un Code Lab**

## Descripción de la Charla Técnica o Code Lab
Veremos los sencillo que es integrar Angular con Apollo y revisaremos que propone Apollo para considerarlo en nuestro Stack. Revisaremos porque Graphql esta revolucionando la forma en la que consumimos datos desde el lado del Cliente y porque esta dando una "Competencia" a REST. El Objetivo es conocer a grandes rasgos lo que es Apollo y su Integración con Angular.

## Acerca de Ti
Kenji es un desarrollador de software, trabajando con javascript desde hace varios años. Fanático por Meteor y Apollo Stack 🚀.

## Username en Twitter
@kenji_lozano

## Username en Slack(Angular Bolivia Team)
@kenji

## Ciudad de Residencia
Cochabamba

## Tiempo 
30min

## Nivel
Basico

## ¿Has dado esta charla antes?
No

**Comment by luixaviles** [comment]
¡Hola @klozano !

Estamos muy contentos de recibir tu propuesta. Pero debido a limitaciones de tiempo para nuestro meetup, no podremos tomarla en cuenta en esta ocasión. Sin embargo, nos gustaría contar con tu participación en nuestro siguiente evento.
Te pedimos que te pongas en contacto con nosotros para poder coordinar y resolver las dudas que tengas.

¡Saludos!
