### ISSUE TITLE
Traducir aplicaciones Angular utilizando ngx-translate

### ISSUE THREAD

**Issue by nativuks** [angular-bolivia/meetup#9]
# Me gustaría...

`(Selecciona con una "x" => [x])`

- [ ] **Dar una Charla Técnica:** 
- [ x] **Dar un Code Lab**

## Descripción de la Charla Técnica o Code Lab
La internacionalizacion de una aplicacion en estos tiempos es una necesidad basica. 
Se mostrará una de las alternativas para tener una aplicación angular multi idioma, utilizando ngx-translate:

## Acerca de Ti
Desarrollador de aplicaciones moviles nativas e hibridas, apasionado por los frameworks web Laravel y Ruby On Rails. Actualmente incursionando en el mundo javascript con: angular, vue js, nodejs, restify.

## Username en Twitter
@nativuks

## Username en Slack(Angular Bolivia Team)
@fsejas

## Ciudad de Residencia
Cochabamba

## Tiempo 
30 minutos

## Nivel
Básico-Intermedio

## ¿Has dado esta charla antes?
 No

**Comment by luixaviles** [comment]
¡Hola @nativuks !

Estamos muy contentos de anunciar que tu propuesta ha sido aceptada por el equipo de organización.
Estaremos coordinando detalles a través de nuestro team en Slack. Te pedimos que te pongas en contacto con nosotros para poder coordinar y resolver las dudas que tengas.

¡Saludos!
